"""Postgres: SQLite DDL-ээс schema бэлтгэх, багана нэмэх, timestamp trigger, sequence тааруулах."""

import re

from core.db import IS_PG, get_db
from core.db.migrate_data import _MIGRATIONS


# ======================= Postgres: schema бэлтгэх =======================
_RE_ID_PK = re.compile(r"\bid(\s+)INTEGER PRIMARY KEY( AUTOINCREMENT)?")
_RE_FK = re.compile(r"^\s*FOREIGN KEY\s*\((?P<cols>[^)]+)\)\s*REFERENCES\s*(?P<ref>[^,]+?),?\s*$",
                    re.MULTILINE)
_RE_TABLE = re.compile(r"CREATE TABLE IF NOT EXISTS\s+(\w+)", re.IGNORECASE)


def _split_statements(script):
    """DDL-ийг мэдэгдэл тус бүрээр нь салгана.

    Энгийн `split(";")` тохирохгүй — тайлбар (`-- ...`) дотор цэг таслал байвал
    мэдэгдлийг дундуур нь тасалчихна. Тиймээс мөр мөрөөр нь явж, тайлбараас
    ГАДУУРХ цэг таслалыг л төгсгөл гэж үзнэ.
    """
    stmts, buf = [], []
    for line in script.split("\n"):
        buf.append(line)
        if ";" in line.split("--")[0]:
            stmts.append("\n".join(buf).rsplit(";", 1)[0])
            buf = []
    if any(l.strip() for l in buf):
        stmts.append("\n".join(buf))
    return stmts


def _strip_dangling_comma(stmt):
    """FK мөрүүдийг хассаны дараа үлдсэн сүүлчийн таслалыг арилгана.

    Тайлбар (`-- ...`) таслалын ард үлддэг тул энгийн regex хүрэлцэхгүй — мөр
    мөрөөр нь явж, агуулгатай СҮҮЛЧИЙН мөрний таслалыг л хасна.
    """
    lines = stmt.split("\n")
    for i in range(len(lines) - 1, -1, -1):
        code = lines[i].split("--")[0].rstrip()
        if not code.strip() or code.strip() == ")":
            continue
        if code.endswith(","):
            lines[i] = code[:-1] + (("  " + lines[i][len(code):].lstrip())
                                    if "--" in lines[i] else "")
        break
    return "\n".join(lines)


def _pg_schema(script):
    """SQLite-ийн DDL-ийг Postgres-ийнх болгож, FK-үүдийг ТУСАД нь салгана.

    Хоёр ялгаа:
      * `id INTEGER PRIMARY KEY [AUTOINCREMENT]` -> IDENTITY (гараас id өгөх ч
        боломжтой хэвээр — лавлахууд id-гаа өөрсдөө заадаг).
      * SQLite нь хожим үүсэх хүснэгт рүү FK бичихийг зөвшөөрдөг, PG зөвшөөрдөггүй.
        Тиймээс FK мөрүүдийг хасаад, бүх хүснэгт үүссэний ДАРАА ALTER-ээр нэмнэ.
    """
    script = _RE_ID_PK.sub(r"id\1INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY", script)
    alters, out = [], []
    for stmt in _split_statements(script):
        if not stmt.strip():
            continue
        m = _RE_TABLE.search(stmt)
        if m:
            table, n = m.group(1), 0
            def take(fk, table=table):
                nonlocal n
                n += 1
                alters.append(
                    f"DO $$ BEGIN ALTER TABLE {table} ADD CONSTRAINT fk_{table}_{n} "
                    f"FOREIGN KEY ({fk.group('cols')}) REFERENCES {fk.group('ref').strip()}; "
                    f"EXCEPTION WHEN duplicate_object THEN NULL; END $$")
                return ""
            stmt = _RE_FK.sub(take, stmt)
            stmt = _strip_dangling_comma(stmt)
        out.append(stmt)
    return ";\n".join(out) + ";", alters


_PG_TS_FN = """
CREATE OR REPLACE FUNCTION set_timestamps() RETURNS trigger AS $$
DECLARE now_txt TEXT := to_char(now() AT TIME ZONE 'utc',
                                'YYYY-MM-DD"T"HH24:MI:SS+00:00');
BEGIN
  IF TG_OP = 'INSERT' THEN
    NEW.created_at := COALESCE(NEW.created_at, now_txt);
    NEW.updated_at := COALESCE(NEW.updated_at, now_txt);
  ELSE
    NEW.created_at := OLD.created_at;
    NEW.updated_at := now_txt;
  END IF;
  RETURN NEW;
END $$ LANGUAGE plpgsql;
"""


def _pg_tables(conn):
    return [r[0] for r in conn.execute(
        "SELECT table_name FROM information_schema.tables "
        "WHERE table_schema='public' AND table_type='BASE TABLE' ORDER BY table_name")]


def _pg_migrate(conn):
    """Хуучин Postgres DB-д дутуу баганыг нөхнө (_MIGRATIONS-ийн PG хувилбар).

    `CREATE TABLE IF NOT EXISTS` нь БАЙГАА хүснэгтийг өөрчилдөггүй тул схемд шинэ
    багана нэмэхэд SQLite тал `_migrate()`-ээр, Postgres тал эндээс нөхөгдөнө.
    `ADD COLUMN IF NOT EXISTS` тул дахин ажиллуулахад аюулгүй.
    """
    existing = set(_pg_tables(conn))
    for table, cols in _MIGRATIONS.items():
        if table not in existing:
            continue
        for name, decl in cols:
            conn.execute(f"ALTER TABLE {table} ADD COLUMN IF NOT EXISTS {name} {decl}")


def _pg_timestamps(conn):
    """Бүх хүснэгтэд created_at/updated_at багана ба тэдгээрийн trigger (PG хувилбар)."""
    conn.executescript(_PG_TS_FN)
    for t in _pg_tables(conn):
        conn.execute(f"ALTER TABLE {t} ADD COLUMN IF NOT EXISTS created_at TEXT")
        conn.execute(f"ALTER TABLE {t} ADD COLUMN IF NOT EXISTS updated_at TEXT")
        conn.execute(f"DROP TRIGGER IF EXISTS trg_{t}_ts ON {t}")
        conn.execute(f"CREATE TRIGGER trg_{t}_ts BEFORE INSERT OR UPDATE ON {t} "
                     f"FOR EACH ROW EXECUTE FUNCTION set_timestamps()")


def pg_sync_sequences(conn=None):
    """IDENTITY дарааллуудыг одоо байгаа хамгийн том id-д тааруулна.

    Лавлахуудын мөрүүд id-гаа гараас авдаг (ж: structure 1..22) тул дараалал нь
    хоцорч үлддэг — үүнийг засахгүй бол дараагийн автомат id давхцана.
    """
    if not IS_PG:
        return
    own = conn is None
    conn = conn or get_db()
    for t in _pg_tables(conn):
        try:
            row = conn.execute(
                "SELECT pg_get_serial_sequence(?, 'id')", (t,)).fetchone()
        except Exception:
            continue                      # id багана байхгүй хүснэгт (ж: admin_unit1)
        seq = row[0] if row else None
        if not seq:
            continue
        conn.execute(f"SELECT setval('{seq}', GREATEST((SELECT COALESCE(MAX(id), 0) FROM {t}), 1))")
    conn.commit()
    if own:
        conn.close()
